---
---
---

```{r}
# Clear working memory
rm(list=ls())
```

```{r}
library(tidyverse)
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(plotly)
library(readxl)
library(xts)
library(TSA)
```

```{r}
# LOAD THE DATA
df_arrival <-read_xlsx('arrival.xlsx')

head(df_arrival)
```

```{r}
# CREATING TIME SERIES DATA
arrival <- ts(df_arrival$arrival, start = c(2000,1), frequency = 12)
head(arrival)
```

```{r}
gfc <- ts(df_arrival$gfc, start = c(2000,1), frequency = 12)
globcci <- ts(df_arrival$globcci, start = c(2000,1), frequency = 12)
geopol <- ts(df_arrival$geopol, start = c(2000,1), frequency = 12)
oil <- ts(df_arrival$oil, start = c(2000,1), frequency = 12)
sars <- ts(df_arrival$sars, start = c(2000,1), frequency = 12)
#gfc_0809 <- ts(df_arrival$gfc_0809, start = c(2000,1), frequency = 12)

# PLOTTING
autoplot(arrival, main = "Monthly Tourist Arrival in Indonesia, January 2000 - December 2019", 
         ylab = "Tourist Arrival", xlab = "Year")
```

```{r}
seasonplot(arrival, main = "Seasonal Plot of Tourist Arrival Indonesia, 
           January 2000 - December 2019")
```

```{r}
# CHECKING THE NORMALITY
hist(arrival, main = "Histogram of Foreign Tourists Arrival in Indonesia,
     January 2000 - December 2019")
```

```{r}
shapiro.test(arrival)
```

```{r}
# CUT AND SPLIT THE DATA
training_arrival <- window(arrival,  start = c(2000,1), end = c(2015,12))
test_arrival <- window(arrival, start= c(2016,1), end = c(2019,12))

training_geopol <- window(geopol,  start = c(2000,1), end = c(2015,12))
test_geopol <- window(geopol, start= c(2016,1), end = c(2019,12))

training_gfc <- window(gfc,  start = c(2000,1), end = c(2015,12))
test_gfc <- window(gfc, start= c(2016,1), end = c(2019,12))

#training_gfc_0809 <- window(gfc_0809,  start = c(2000,1), end = c(2015,12))
#test_gfc_0809 <- window(gfc_0809, start= c(2016,1), end = c(2019,12))

training_globcci <- window(globcci,  start = c(2000,1), end = c(2015,12))
test_globcci <- window(globcci, start= c(2016,1), end = c(2019,12))

training_oil <- window(oil,  start = c(2000,1), end = c(2015,12))
test_oil <- window(oil, start= c(2016,1), end = c(2019,12))

training_sars <- window(sars,  start = c(2000,1), end = c(2015,12))
test_sars <- window(sars, start= c(2016,1), end = c(2019,12))

autoplot(training_arrival)
```

```{r}
autoplot(test_arrival)
```

```{r}
seasonplot(training_arrival)
```

```{r}
# CHECKING THE NORMALITY
hist(training_arrival, main = "Histogram of Foreign Tourists Arrival in Indonesia,
     January 2000 - December 2015")
```

```{r}
shapiro.test(training_arrival)
```

```{r}
# CHECKING STATIONARITY
tsdisplay(training_arrival, main = "ACF and PACF for Foreign Tourists Arrival in Indonesia,
     January 2000 - December 2015")
```

```{r}
acf(training_arrival)
```

```{r}
pacf(training_arrival)
```

```{r}
kpss.test(training_arrival)
```

```{r}
adf.test(training_arrival)
```

```{r}
# BOX COX TRANSFORMATION
auto_lambda <- BoxCox.lambda(training_arrival)
auto_lambda
```

```{r}
training_arrival_bcauto <- BoxCox(training_arrival,auto_lambda)
plot(training_arrival_bcauto)
```

```{r}
hist(training_arrival_bcauto)
```

```{r}
shapiro.test(training_arrival_bcauto)
```

```{r}
kpss.test(training_arrival_bcauto, null=c("Level"))
```

```{r}
acf(training_arrival_bcauto)
```

```{r}
pacf(training_arrival_bcauto)
```

```{r}
eacf(training_arrival_bcauto)
```

```{r}
#BENCHMARK ETS MODEL NO LAMBDA
#Error type: Additive
#Trend type: None
#Season type: Additive

#model
model_ets_0 <- ets(training_arrival)
fcast_ets_0 <- forecast(model_ets_0, h=48)
summary(model_ets_0)
```

```{r}
aicc_ets_0 <- model_ets_0$aicc
bic_ets_0 <- model_ets_0$bic
checkresiduals(model_ets_0)
```

```{r}
#accuracy forecast
accuracy_ets_0 <- accuracy(fcast_ets_0, test_arrival)
accuracy_ets_0
```

```{r}
rmse_ets_0 <- accuracy_ets_0[4]
mape_ets_0 <- accuracy_ets_0[10]
mse_ets_0 <- mean(abs((test_arrival - fcast_ets_0$mean))^2)

#plot
max_test_arrival <- max(test_arrival)
min_value <- min(training_arrival)
custom_y_limits <- c(min_value, max_test_arrival)
plot(fcast_ets_0, type = "l", col = "blue", lwd = 2, xlab = "Time", ylab = "Values", main = "Forecast Plot", ylim = custom_y_limits)
lines(test_arrival, type = "l", col = "red", lwd = 2)
grid()
legend("topleft", legend = c("Forecast", "Test Arrival"), col = c("blue", "red"), lty = 1, lwd = 2)
```

```{r}
#Comparison
compare_accuracy <- data.frame(Model = c("model:ETS - NO LAMBDA SPECIFICATION"),
                               AIC = c(aicc_ets_0),
                               BIC = c(bic_ets_0),
                               RMSE = c(rmse_ets_0),
                               MAPE = c(mape_ets_0),
                               MSE = c(mse_ets_0))

compare_accuracy
```

```{r}
#BENCHMARK ETS MODEL LAMBDA AUTO
#Error type: Additive
#Trend type: None
#Season type: Additive

#model
model_ets_1 <- ets(training_arrival, lambda = "auto")
fcast_ets_1 <- forecast(model_ets_1, h=48)
summary(model_ets_1)
```

```{r}
aicc_ets_1 <- model_ets_1$aicc
bic_ets_1 <- model_ets_1$bic
checkresiduals(model_ets_1)
```

```{r}
#accuracy forecast
accuracy_ets_1 <- accuracy(fcast_ets_1, test_arrival)
accuracy_ets_1
```

```{r}
rmse_ets_1 <- accuracy_ets_1[4]
mape_ets_1 <- accuracy_ets_1[10]
mse_ets_1 <- mean(abs((test_arrival - fcast_ets_1$mean))^2)

#plot
max_test_arrival <- max(test_arrival)
min_value <- min(training_arrival)
custom_y_limits <- c(min_value, max_test_arrival)
plot(fcast_ets_1, type = "l", col = "blue", lwd = 2, xlab = "Time", ylab = "Values", main = "Forecast Plot", ylim = custom_y_limits)
lines(test_arrival, type = "l", col = "red", lwd = 2)
grid()
legend("topleft", legend = c("Forecast", "Test Arrival"), col = c("blue", "red"), lty = 1, lwd = 2)
```

```{r}
#Comparison
compare_accuracy <- data.frame(Model = c("model:ETS - LAMBDA AUTO"),
                               AIC = c(aicc_ets_1),
                               BIC = c(bic_ets_1),
                               RMSE = c(rmse_ets_1),
                               MAPE = c(mape_ets_1),
                               MSE = c(mse_ets_1))

compare_accuracy
```

```{r}
#BENCHMARK ETS MODEL LAMBDA 0
#Error type: Additive
#Trend type: Additive
#Season type: Additive

#model
model_ets_2 <- ets(training_arrival, lambda = 0)
fcast_ets_2 <- forecast(model_ets_2, h=48)
summary(model_ets_2)
```

```{r}
aicc_ets_2 <- model_ets_2$aicc
bic_ets_2 <- model_ets_2$bic

checkresiduals(model_ets_2)
```

```{r}
#accuracy forecast
accuracy_ets_2 <- accuracy(fcast_ets_2, test_arrival)
accuracy_ets_2
```

```{r}
rmse_ets_2 <- accuracy_ets_2[4]
mape_ets_2 <- accuracy_ets_2[10]
mse_ets_2 <- mean(abs((test_arrival - fcast_ets_2$mean))^2)

#plot
plot(fcast_ets_2, type = "l", col = "blue", lwd = 2, xlab = "Time", ylab = "Values", main = "Forecast Plot", ylim = custom_y_limits)
lines(test_arrival, type = "l", col = "red", lwd = 2)
grid()
legend("topleft", legend = c("Forecast", "Test Arrival"), col = c("blue", "red"), lty = 1, lwd = 2)
```

```{r}
#Comparison
compare_accuracy <- data.frame(Model = c("model:ETS - LAMBDA AUTO", "model: ETS - LAMBDA 0"),
                               AIC = c(aicc_ets_1, aicc_ets_2),
                               BIC = c(bic_ets_1, bic_ets_2),
                               RMSE = c(rmse_ets_1, rmse_ets_2),
                               MAPE = c(mape_ets_1, mape_ets_2),
                               MSE = c(mse_ets_1, mse_ets_2))

compare_accuracy
```

```{r}
#BENCHMARK ETS MODEL - lambda = 0.5
#Error type: Additive
#Trend type: Additive
#Season type: Additive

#model
model_ets_3 <- ets(training_arrival, lambda = 0.5)
fcast_ets_3 <- forecast(model_ets_3, h=48)
summary(model_ets_3)
```

```{r}
aicc_ets_3 <- model_ets_3$aicc
bic_ets_3 <- model_ets_3$bic

checkresiduals(model_ets_3)
```

```{r}
#accuracy forecast
accuracy_ets_3 <- accuracy(fcast_ets_3, test_arrival)
accuracy_ets_3
```

```{r}
rmse_ets_3 <- accuracy_ets_3[4]
mape_ets_3 <- accuracy_ets_3[10]
mse_ets_3 <- mean(abs((test_arrival - fcast_ets_3$mean))^2)

#plot
plot(fcast_ets_3, type = "l", col = "blue", lwd = 2, xlab = "Time", ylab = "Values", main = "Forecast Plot", ylim = custom_y_limits)
lines(test_arrival, type = "l", col = "red", lwd = 2)
grid()
legend("topleft", legend = c("Forecast", "Test Arrival"), col = c("blue", "red"), lty = 1, lwd = 2)
```

```{r}
#Comparison
compare_accuracy <- data.frame(Model = c("model:ETS - Auto", "model: ETS - 0", "model: ETS - 0.5"),
                               AIC = c(aicc_ets_1, aicc_ets_2, aicc_ets_3),
                               BIC = c(bic_ets_1, bic_ets_2, bic_ets_3),
                               RMSE = c(rmse_ets_1, rmse_ets_2, rmse_ets_3),
                               MAPE = c(mape_ets_1, mape_ets_2, mape_ets_3),
                               MSE = c(mse_ets_1, mse_ets_2, mse_ets_3))

compare_accuracy
```
